# Classification: Fire And Not Fire

- Operation Performed

    1. Data Cleaning 
    2. EDA
    3. Feature Engineering
    4. Model Training 
    5. Tuning

---

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [11]:
dataset = pd.read_csv('Algerian_forest_fires_dataset_UPDATE.csv', header = 1)
dataset.head(3)

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
0,01,06,2012,29,57,18,0,65.7,3.4,7.6,1.3,3.4,0.5,not fire
1,02,06,2012,29,61,13,1.3,64.4,4.1,7.6,1,3.9,0.4,not fire
2,03,06,2012,26,82,22,13.1,47.1,2.5,7.1,0.3,2.7,0.1,not fire

# Dataset Cleaning

- Dataset is in two parts (Region)
- Merge them with a category 0 & 1 as per Region: (:122) as 0,  (122:) as 1 and Merge

In [13]:
dataset[dataset.isnull().any(axis=1)]

,day,month,year,Temperature,RH,Ws,Rain,FFMC,DMC,DC,ISI,BUI,FWI,Classes
122,Sidi-Bel Abbes Region Dataset,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
167,14,07,2012,37,37,18,0.2,88.9,12.9,14.6 9,12.5,10.4,fire,NaN

In [14]:
df = dataset
df.loc[:122, "Region"] = 0
df.loc[122:, "Region"] = 1

df[["Region"]] = df[["Region"]].astype(int)